"""
LLM-Assisted Reagent Registry Review
====================================

Provides helper utilities to run a language-model review of reagent taxonomy
entries generated by deterministic chemtools pipelines. This module keeps the
UI code lightweight and makes it easy to unit test by injecting stub clients.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Any, Dict, Iterable, List, Optional

from llmtools.clients import LLMClient
from llmtools.prompts import REAGENT_REGISTRY_REVIEW


def _format_list(values: Iterable[Any]) -> str:
    """Render iterable values as a comma-separated string for prompt filling."""
    items = [str(value) for value in values if value]
    return ", ".join(items) if items else "None"


def _format_debug_log(entries: Iterable[str]) -> str:
    """Summarize debug log entries for the LLM prompt."""
    items = [entry.strip() for entry in entries if entry]
    if not items:
        return "[]"
    return json.dumps(items, ensure_ascii=False)


def _strip_markdown_fences(content: str) -> str:
    """
    Remove markdown code fences from LLM response.
    
    Some LLM providers (especially DeepSeek) wrap JSON in ```json ... ``` fences.
    This function extracts the content between fences.
    """
    content = content.strip()
    
    # Check for markdown code fence with language specifier
    if content.startswith("```json") or content.startswith("```JSON"):
        # Remove opening fence
        content = content[7:].lstrip()
    elif content.startswith("```"):
        # Remove opening fence without language
        content = content[3:].lstrip()
    
    # Remove closing fence
    if content.endswith("```"):
        content = content[:-3].rstrip()
    
    return content.strip()


@dataclass
class LLMReviewOptions:
    """Runtime configuration for the LLM-backed registry review."""

    enabled: bool = False
    provider: Optional[str] = None
    model: Optional[str] = None
    temperature: float = 0.0
    max_tokens: int = 800
    timeout: int = 60

    def is_ready(self) -> bool:
        """Return True if the configuration is usable for an LLM call."""
        return bool(self.enabled and self.provider and self.model)


def build_review_prompt(context: Dict[str, Any]) -> str:
    """Construct the structured review prompt from the deterministic context."""

    family_entry: Dict[str, Any] = context.get("family_entry", {}) or {}
    resolver_info: Dict[str, Any] = context.get("resolved_identity", {}) or {}
    existing_other_roles = context.get("existing_other_roles") or []

    return REAGENT_REGISTRY_REVIEW.format(
        name=context.get("name", "Unknown"),
        cas=context.get("cas", "Unknown"),
        synonyms=_format_list(context.get("synonyms", [])),
        abbreviations=_format_list(context.get("abbreviations", [])),
        resolver_source=resolver_info.get("source", "Unknown"),
        resolver_name=resolver_info.get("name", "Unknown"),
        resolver_smiles=resolver_info.get("smiles", "Unknown"),
        family_tokens=context.get("family_reason") or [],
        used_default_family=context.get("used_default_family", False),
        debug_log=_format_debug_log(context.get("debug_log", [])),
        role=context.get("role", "Unknown"),
        family_id=context.get("family_id", "Unknown"),
        family_definition=family_entry.get("definition", "Not available"),
        family_notes=family_entry.get("notes", "Not available"),
        family_keywords=_format_list(family_entry.get("keywords", [])),
        family_examples=_format_list(family_entry.get("examples_pos", [])),
        existing_same_role=context.get("existing_same_role") or "None",
        existing_other_roles=_format_list(existing_other_roles),
    )


def review_taxonomy_proposal(
    context: Dict[str, Any],
    options: LLMReviewOptions,
    client: Optional[LLMClient] = None,
) -> Dict[str, Any]:
    """
    Run an LLM-powered review of a proposed reagent registry entry.

    Args:
        context: Deterministic inference context from registry pipeline.
        options: LLM configuration flags.
        client: Optional pre-configured LLMClient (useful for tests).

    Returns:
        Dict with normalized review information; includes the raw response and
        metadata even if parsing fails so the UI can surface diagnostics.
    """
    if not options.is_ready():
        return {"enabled": False, "reason": "disabled"}

    prompt = build_review_prompt(context)

    llm_client = client
    if llm_client is None:
        llm_client = LLMClient(
            provider=options.provider or "openai",
            model=options.model,
            temperature=options.temperature,
            max_tokens=options.max_tokens,
            timeout=options.timeout,
        )

    try:
        response = llm_client.chat(
            prompt=prompt,
            temperature=options.temperature,
            max_tokens=options.max_tokens,
        )
    except Exception as exc:  # noqa: BLE001 - surface up to UI
        return {
            "enabled": True,
            "status": "error",
            "error": str(exc),
            "provider": options.provider,
            "model": options.model,
        }

    raw_content = (response.content or "").strip()
    parsed: Optional[Dict[str, Any]] = None
    parse_error: Optional[str] = None

    if raw_content:
        # Strip markdown code fences that some LLMs add
        cleaned_content = _strip_markdown_fences(raw_content)
        try:
            parsed = json.loads(cleaned_content)
        except json.JSONDecodeError as exc:
            parse_error = f"{exc.__class__.__name__}: {exc}"

    normalized_alerts: List[str] = []
    if parsed and isinstance(parsed.get("alerts"), list):
        normalized_alerts = [str(item) for item in parsed["alerts"] if item]

    result = {
        "enabled": True,
        "status": "ok" if parsed else "parse_error",
        "provider": options.provider,
        "model": response.model,
        "raw_response": raw_content,
        "prompt_tokens": response.prompt_tokens,
        "completion_tokens": response.completion_tokens,
        "total_tokens": response.total_tokens,
        "latency_ms": response.latency_ms,
        "analysis": None,
    }

    if parse_error:
        result["error"] = parse_error

    if parsed:
        result["analysis"] = {
            "status": parsed.get("status"),
            "proposed_role": parsed.get("proposed_role"),
            "proposed_family": parsed.get("proposed_family"),
            "confidence": parsed.get("confidence"),
            "justification": parsed.get("justification"),
            "alerts": normalized_alerts,
            "suggested_synonyms": [
                str(value) for value in parsed.get("suggested_synonyms", []) or []
            ],
            "field_suggestions": parsed.get("field_suggestions", {}),
        }

    return result


__all__ = [
    "LLMReviewOptions",
    "build_review_prompt",
    "review_taxonomy_proposal",
]
