"""Sample Compounds Data
====================

This file contains comprehensive sample compound SMILES with known reaction types
for testing the calculable features detection system and reaction classification.

Each compound is annotated with:
- SMILES string
- Common name or description
- Typical reaction role (electrophile, nucleophile, coupling partner)
- Expected reaction types
- Key structural features"""

from typing import Dict, List, Any

ARYL_HALIDES = [
    {
        "features": ["ArBr_reactant"],
        "name": "Bromobenzene",
        "notes": "Standard aryl bromide for all cross-coupling reactions",
        "reaction_types": [
            "Suzuki-Miyaura",
            "Buchwald-Hartwig",
            "Ullmann",
            "Sonogashira",
            "Heck",
            "Stille",
            "Negishi",
            "Kumada",
        ],
        "role": "electrophile",
        "smiles": "Brc1ccccc1",
    },
    {
        "features": ["ArCl_reactant"],
        "name": "Chlorobenzene",
        "notes": "Less reactive; requires activated catalyst systems",
        "reaction_types": [
            "Suzuki-Miyaura",
            "Buchwald-Hartwig",
            "Ullmann",
            "Sonogashira",
            "Heck",
        ],
        "role": "electrophile",
        "smiles": "Clc1ccccc1",
    },
    {
        "features": ["ArI_reactant"],
        "name": "Iodobenzene",
        "notes": "Most reactive aryl halide",
        "reaction_types": [
            "Suzuki-Miyaura",
            "Buchwald-Hartwig",
            "Sonogashira",
            "Heck",
            "Stille",
            "Negishi",
            "Kumada",
        ],
        "role": "electrophile",
        "smiles": "Ic1ccccc1",
    },
    {
        "features": ["ArF_reactant"],
        "name": "Fluorobenzene",
        "notes": "Requires strong nucleophiles for SNAr; not for standard cross-coupling",
        "reaction_types": ["SNAr"],
        "role": "electrophile",
        "smiles": "Fc1ccccc1",
    },
    {
        "features": ["Ar-CN_reactant", "ArBr_reactant"],
        "name": "4-Bromobenzonitrile",
        "notes": "Electron-poor aryl bromide; more reactive",
        "reaction_types": ["Suzuki-Miyaura", "Buchwald-Hartwig", "Sonogashira"],
        "role": "electrophile",
        "smiles": "Brc1ccc(C#N)cc1",
    },
    {
        "features": ["Alkyl-H_reactant", "ArBr_reactant"],
        "name": "4-Bromoanisole",
        "notes": "Electron-rich aryl bromide; standard substrate",
        "reaction_types": ["Suzuki-Miyaura", "Buchwald-Hartwig", "Sonogashira", "Heck"],
        "role": "electrophile",
        "smiles": "Brc1ccc(OC)cc1",
    },
    {
        "features": ["ArBr_reactant"],
        "name": "4-Bromonitrobenzene",
        "notes": "Highly electron-poor; very reactive",
        "reaction_types": ["Suzuki-Miyaura", "Buchwald-Hartwig", "SNAr"],
        "role": "electrophile",
        "smiles": "Brc1ccc([N+](=O)[O-])cc1",
    },
    {
        "features": ["ArBr_reactant"],
        "name": "4-Bromobenzotrifluoride",
        "notes": "Electron-poor CF3 substituent",
        "reaction_types": ["Suzuki-Miyaura", "Buchwald-Hartwig", "Sonogashira"],
        "role": "electrophile",
        "smiles": "Brc1ccc(C(F)(F)F)cc1",
    },
    {
        "features": ["ArBr_reactant"],
        "name": "1,3,5-Tribromobenzene",
        "notes": "Multiple coupling sites; sp2_halide_site_count = 3",
        "reaction_types": ["Suzuki-Miyaura", "Buchwald-Hartwig"],
        "role": "electrophile",
        "smiles": "Brc1cc(Br)cc(Br)c1",
    },
    {
        "features": ["ArCl_reactant"],
        "name": "1,4-Dichlorobenzene",
        "notes": "Di-functionalization substrate",
        "reaction_types": ["Suzuki-Miyaura", "Buchwald-Hartwig"],
        "role": "electrophile",
        "smiles": "Clc1ccc(Cl)cc1",
    },
    {
        "features": ["Alkyl-H_reactant", "ArBr_reactant", "Bn-Br_reactant"],
        "name": "2-Bromotoluene",
        "notes": "Ortho-substituted; sterically hindered",
        "reaction_types": ["Suzuki-Miyaura", "Buchwald-Hartwig"],
        "role": "electrophile",
        "smiles": "Brc1ccccc1C",
    },
    {
        "features": ["Alkyl-H_reactant", "ArBr_reactant", "Bn-Br_reactant"],
        "name": "3,5-Dimethylbromobenzene",
        "notes": "Meta-substituted; moderate sterics",
        "reaction_types": ["Suzuki-Miyaura", "Buchwald-Hartwig"],
        "role": "electrophile",
        "smiles": "Brc1cc(C)cc(C)c1",
    },
    {
        "features": ["Alkyl-H_reactant", "ArBr_reactant", "Bn-Br_reactant"],
        "name": "Pentamethylbromobenzene",
        "notes": "Highly sterically hindered",
        "reaction_types": ["Suzuki-Miyaura"],
        "role": "electrophile",
        "smiles": "Brc1c(C)c(C)c(C)c(C)c1C",
    },
    {
        "features": ["ArBr_reactant"],
        "name": "2-Bromonaphthalene",
        "notes": "Fused aromatic system",
        "reaction_types": ["Suzuki-Miyaura", "Buchwald-Hartwig", "Sonogashira"],
        "role": "electrophile",
        "smiles": "Brc1ccc2ccccc2c1",
    },
    {
        "features": ["ArCl_reactant"],
        "name": "2-Chloronaphthalene",
        "notes": "Activated chloride on naphthalene",
        "reaction_types": ["Suzuki-Miyaura", "Buchwald-Hartwig"],
        "role": "electrophile",
        "smiles": "Clc1ccc2ccccc2c1",
    },
    {
        "features": ["ArBr_reactant"],
        "name": "1-Bromonaphthalene",
        "notes": "Peri-position naphthyl bromide",
        "reaction_types": ["Suzuki-Miyaura", "Buchwald-Hartwig"],
        "role": "electrophile",
        "smiles": "Brc1cccc2c1cccc2",
    },
    {
        "features": ["ArBr_reactant"],
        "name": "4-Bromopyridine",
        "notes": "Heteroaryl halide; pyridine can poison some catalysts",
        "reaction_types": [
            "Suzuki-Miyaura",
            "Buchwald-Hartwig",
            "Sonogashira",
            "Stille",
            "Negishi",
        ],
        "role": "electrophile",
        "smiles": "Brc1ccncc1",
    },
    {
        "features": ["ArBr_reactant"],
        "name": "3-Bromopyridine",
        "notes": "Meta-bromo pyridine",
        "reaction_types": ["Suzuki-Miyaura", "Buchwald-Hartwig", "Sonogashira"],
        "role": "electrophile",
        "smiles": "Brc1cccnc1",
    },
    {
        "features": ["ArBr_reactant", "HetArBr_reactant", "PyridineBr_reactant"],
        "name": "2-Bromopyridine",
        "notes": "Ortho-bromo pyridine; strong chelation",
        "reaction_types": ["Suzuki-Miyaura", "Buchwald-Hartwig", "Sonogashira"],
        "role": "electrophile",
        "smiles": "Brc1ccccn1",
    },
    {
        "features": ["ArCl_reactant"],
        "name": "4-Chloropyridine",
        "notes": "Activated heterocyclic chloride",
        "reaction_types": ["Suzuki-Miyaura", "Buchwald-Hartwig"],
        "role": "electrophile",
        "smiles": "Clc1ccncc1",
    },
    {
        "features": ["ArBr_reactant", "HetArBr_reactant"],
        "name": "5-Bromopyrimidine",
        "notes": "Diazine substrate",
        "reaction_types": ["Suzuki-Miyaura", "Buchwald-Hartwig"],
        "role": "electrophile",
        "smiles": "Brc1cnccn1",
    },
    {
        "features": ["ArBr_reactant"],
        "name": "2-Bromothiophene",
        "notes": "Five-membered heterocycle",
        "reaction_types": ["Suzuki-Miyaura", "Sonogashira", "Stille"],
        "role": "electrophile",
        "smiles": "Brc1cccs1",
    },
    {
        "features": ["ArBr_reactant", "furan-diene_reactant"],
        "name": "2-Bromofuran",
        "notes": "Oxygen heterocycle",
        "reaction_types": ["Suzuki-Miyaura", "Sonogashira"],
        "role": "electrophile",
        "smiles": "Brc1ccco1",
    },
    {
        "features": ["ArBr_reactant"],
        "name": "3-Bromopyrrole",
        "notes": "NH heterocycle; acidic proton",
        "reaction_types": ["Suzuki-Miyaura"],
        "role": "electrophile",
        "smiles": "Brc1cc[nH]c1",
    },
    {
        "features": ["ArBr_reactant"],
        "name": "5-Bromoindole",
        "notes": "Indole scaffold; NH can coordinate",
        "reaction_types": ["Suzuki-Miyaura", "Buchwald-Hartwig", "Sonogashira"],
        "role": "electrophile",
        "smiles": "Brc1ccc2[nH]ccc2c1",
    },
    {
        "features": ["ArBr_reactant", "ThiazoleBr_reactant"],
        "name": "2-Bromobenzothiazole",
        "notes": "Fused bicyclic heterocycle",
        "reaction_types": ["Suzuki-Miyaura", "Buchwald-Hartwig"],
        "role": "electrophile",
        "smiles": "Brc1nc2ccccc2s1",
    },
    {
        "features": ["ArI_reactant"],
        "name": "2-Iodobenzoxazole",
        "notes": "Oxygen-containing fused heterocycle",
        "reaction_types": ["Suzuki-Miyaura", "Buchwald-Hartwig"],
        "role": "electrophile",
        "smiles": "Ic1nc2ccccc2o1",
    },
    {
        "features": ["ArBr_reactant"],
        "name": "3-Bromoquinoline",
        "notes": "Quinoline scaffold",
        "reaction_types": ["Suzuki-Miyaura", "Buchwald-Hartwig"],
        "role": "electrophile",
        "smiles": "Brc1ccnc2ccccc12",
    },
    {
        "features": ["ArBr_reactant", "HetArBr_reactant"],
        "name": "3-Bromoquinoxaline",
        "notes": "Diaza-naphthalene",
        "reaction_types": ["Suzuki-Miyaura"],
        "role": "electrophile",
        "smiles": "Brc1cnc2ccccc2n1",
    },
    {
        "features": ["ArCl_reactant", "HetArCl_reactant"],
        "name": "2,5-Dichloropyridine",
        "notes": "Selective coupling possible at different positions",
        "reaction_types": ["Suzuki-Miyaura", "Buchwald-Hartwig"],
        "role": "electrophile",
        "smiles": "Clc1ccc(Cl)nc1",
    },
    {
        "features": ["ArOSO2R_reactant"],
        "name": "Phenyl triflate",
        "notes": "Excellent leaving group; very reactive",
        "reaction_types": ["Suzuki-Miyaura", "Buchwald-Hartwig", "Sonogashira", "Heck"],
        "role": "electrophile",
        "smiles": "c1ccc(OS(=O)(=O)C(F)(F)F)cc1",
    },
    {
        "features": ["Alkyl-H_reactant", "ArOSO2R_reactant"],
        "name": "4-Methoxyphenyl triflate",
        "notes": "Electron-rich triflate",
        "reaction_types": ["Suzuki-Miyaura", "Buchwald-Hartwig"],
        "role": "electrophile",
        "smiles": "COc1ccc(OS(=O)(=O)C(F)(F)F)cc1",
    },
    {
        "features": ["Alkyl-H_reactant", "ArOSO2R_reactant", "ArOTs_reactant"],
        "name": "Phenyl tosylate",
        "notes": "Good leaving group; cheaper than triflate",
        "reaction_types": ["Suzuki-Miyaura", "Buchwald-Hartwig"],
        "role": "electrophile",
        "smiles": "c1ccc(OS(=O)(=O)c2ccc(C)cc2)cc1",
    },
    {
        "features": ["Alkyl-H_reactant", "ArOMs_reactant", "ArOSO2R_reactant"],
        "name": "Phenyl mesylate",
        "notes": "Mesylate leaving group",
        "reaction_types": ["Suzuki-Miyaura", "Buchwald-Hartwig"],
        "role": "electrophile",
        "smiles": "c1ccc(OS(=O)(=O)C)cc1",
    },
    {
        "features": ["Ar-CN_reactant", "ArOSO2R_reactant"],
        "name": "4-Cyanophenyl triflate",
        "notes": "Electron-poor triflate; highly reactive",
        "reaction_types": ["Suzuki-Miyaura", "Buchwald-Hartwig"],
        "role": "electrophile",
        "smiles": "N#Cc1ccc(OS(=O)(=O)C(F)(F)F)cc1",
    },
    {
        "features": ["alkene-Br_reactant", "simple-dienophile_reactant"],
        "name": "Vinyl bromide",
        "notes": "Simple vinyl halide",
        "reaction_types": [
            "Suzuki-Miyaura",
            "Sonogashira",
            "Heck",
            "Stille",
            "Negishi",
            "Kumada",
        ],
        "role": "electrophile",
        "smiles": "C=CBr",
    },
    {
        "features": ["alkene-Cl_reactant", "simple-dienophile_reactant"],
        "name": "Vinyl chloride",
        "notes": "Less reactive vinyl halide",
        "reaction_types": ["Suzuki-Miyaura", "Heck"],
        "role": "electrophile",
        "smiles": "C=CCl",
    },
    {
        "features": ["alkene-I_reactant", "simple-dienophile_reactant"],
        "name": "Vinyl iodide",
        "notes": "Most reactive vinyl halide",
        "reaction_types": ["Suzuki-Miyaura", "Sonogashira", "Heck", "Stille"],
        "role": "electrophile",
        "smiles": "C=CI",
    },
    {
        "features": [
            "Alkyl-H_reactant",
            "Allyl-Br_reactant",
            "alkene-Br_reactant",
            "simple-dienophile_reactant",
        ],
        "name": "(E)-1-Bromopropene",
        "notes": "Stereodefined vinyl bromide",
        "reaction_types": ["Suzuki-Miyaura", "Sonogashira", "Heck"],
        "role": "electrophile",
        "smiles": "C/C=C/Br",
    },
    {
        "features": [
            "Alkyl-H_reactant",
            "Allyl-Br_reactant",
            "alkene-Br_reactant",
            "simple-dienophile_reactant",
            "terminal-alkene_reactant",
        ],
        "name": "2-Bromopropene",
        "notes": "Geminal disubstituted vinyl bromide",
        "reaction_types": ["Suzuki-Miyaura", "Sonogashira"],
        "role": "electrophile",
        "smiles": "C=C(Br)C",
    },
    {
        "features": [
            "Ar-alkene_reactant",
            "alkene-Br_reactant",
            "simple-dienophile_reactant",
            "terminal-alkene_reactant",
        ],
        "name": "α-Bromostyrene",
        "notes": "Aryl-substituted vinyl bromide",
        "reaction_types": ["Suzuki-Miyaura", "Sonogashira"],
        "role": "electrophile",
        "smiles": "BrC(=C)c1ccccc1",
    },
    {
        "features": ["Alkyl-Br_reactant", "Alkyl-H_reactant"],
        "name": "Ethyl bromide",
        "notes": "Simple primary alkyl bromide; β-hydride elimination risk",
        "reaction_types": ["Suzuki-Miyaura", "Negishi", "Kumada", "SN2"],
        "role": "electrophile",
        "smiles": "CCBr",
    },
    {
        "features": ["Alkyl-Cl_reactant", "Alkyl-H_reactant"],
        "name": "Ethyl chloride",
        "notes": "Primary alkyl chloride",
        "reaction_types": ["Negishi", "Kumada", "SN2"],
        "role": "electrophile",
        "smiles": "CCCl",
    },
    {
        "features": ["Alkyl-H_reactant", "Alkyl-I_reactant"],
        "name": "Ethyl iodide",
        "notes": "Most reactive primary alkyl halide",
        "reaction_types": ["Suzuki-Miyaura", "Negishi", "Kumada", "SN2"],
        "role": "electrophile",
        "smiles": "CCI",
    },
    {
        "features": ["Alkyl-Br_reactant", "Alkyl-H_reactant"],
        "name": "Isopropyl bromide",
        "notes": "Secondary alkyl bromide; high β-hydride risk",
        "reaction_types": ["Negishi", "Kumada"],
        "role": "electrophile",
        "smiles": "CC(C)Br",
    },
    {
        "features": ["Alkyl-Br_reactant", "Alkyl-H_reactant"],
        "name": "tert-Butyl bromide",
        "notes": "Tertiary alkyl bromide; no β-hydride; SN1 mechanism",
        "reaction_types": ["SN1"],
        "role": "electrophile",
        "smiles": "CC(C)(C)Br",
    },
    {
        "features": ["Alkyl-Br_reactant", "Alkyl-H_reactant", "Bn-Br_reactant"],
        "name": "Benzyl bromide",
        "notes": "Benzylic position; activated sp3 halide",
        "reaction_types": ["Suzuki-Miyaura", "SN2", "Negishi"],
        "role": "electrophile",
        "smiles": "BrCc1ccccc1",
    },
    {
        "features": ["Alkyl-Br_reactant", "Alkyl-H_reactant", "Bn-Br_reactant"],
        "name": "2-Phenylethyl bromide",
        "notes": "Primary alkyl bromide with aryl substituent",
        "reaction_types": ["SN2", "Negishi", "Kumada"],
        "role": "electrophile",
        "smiles": "C(Br)Cc1ccccc1",
    },
    {
        "features": [
            "Alkyl-Br_reactant",
            "Alkyl-H_reactant",
            "Allyl-Br_reactant",
            "simple-dienophile_reactant",
            "terminal-alkene_reactant",
        ],
        "name": "4-Bromo-1-butene",
        "notes": "Homoallylic bromide",
        "reaction_types": ["SN2", "Negishi"],
        "role": "electrophile",
        "smiles": "C=CCCBr",
    },
    {
        "features": [
            "Alkyl-Br_reactant",
            "Alkyl-H_reactant",
            "Allyl-Br_reactant",
            "simple-dienophile_reactant",
            "terminal-alkene_reactant",
        ],
        "name": "3-Bromo-2-methylpropene (allylic)",
        "notes": "Allylic bromide; can undergo allylic substitution",
        "reaction_types": ["SN2", "Allylic-substitution"],
        "role": "electrophile",
        "smiles": "C=C(C)CBr",
    },
    {
        "features": ["Alkyl-Br_reactant", "Alkyl-H_reactant"],
        "name": "Neopentyl bromide",
        "notes": "No β-hydrogens; minimal elimination risk",
        "reaction_types": ["Suzuki-Miyaura", "Negishi"],
        "role": "electrophile",
        "smiles": "CC(C)(C)CBr",
    },
    {
        "features": ["ArB(OH)2_reactant"],
        "name": "Phenylboronic acid",
        "notes": "Standard boronic acid coupling partner",
        "reaction_types": ["Suzuki-Miyaura"],
        "role": "nucleophile",
        "smiles": "c1ccc(B(O)O)cc1",
    },
    {
        "features": ["Alkyl-H_reactant", "ArB(OH)2_reactant"],
        "name": "4-Methoxyphenylboronic acid",
        "notes": "Electron-rich boronic acid",
        "reaction_types": ["Suzuki-Miyaura"],
        "role": "nucleophile",
        "smiles": "COc1ccc(B(O)O)cc1",
    },
    {
        "features": ["Ar-CN_reactant", "ArB(OH)2_reactant"],
        "name": "4-Cyanophenylboronic acid",
        "notes": "Electron-poor boronic acid",
        "reaction_types": ["Suzuki-Miyaura"],
        "role": "nucleophile",
        "smiles": "N#Cc1ccc(B(O)O)cc1",
    },
    {
        "features": ["Alkyl-H_reactant", "ArB(OR)2_reactant"],
        "name": "Phenylboronic acid pinacol ester",
        "notes": "Protected boronic acid; more stable",
        "reaction_types": ["Suzuki-Miyaura"],
        "role": "nucleophile",
        "smiles": "c1ccc(B2OC(C)(C)C(C)(C)O2)cc1",
    },
    {
        "features": ["ArBF3K_reactant"],
        "name": "Potassium phenyltrifluoroborate",
        "notes": "BF3K salt; air-stable boronate",
        "reaction_types": ["Suzuki-Miyaura"],
        "role": "nucleophile",
        "smiles": "c1ccc([B-](F)(F)F)cc1.[K+]",
    },
    {
        "features": ["alkeneB(OH)2_reactant", "simple-dienophile_reactant"],
        "name": "Vinylboronic acid",
        "notes": "Vinyl boronic acid",
        "reaction_types": ["Suzuki-Miyaura"],
        "role": "nucleophile",
        "smiles": "C=CB(O)O",
    },
    {
        "features": [
            "Alkyl-H_reactant",
            "alkeneB(OH)2_reactant",
            "simple-dienophile_reactant",
        ],
        "name": "(E)-Propenylboronic acid",
        "notes": "Stereodefined vinyl boronic acid",
        "reaction_types": ["Suzuki-Miyaura"],
        "role": "nucleophile",
        "smiles": "C/C=C/B(O)O",
    },
    {
        "features": ["Alkyl-B(OH)2_reactant", "Alkyl-H_reactant"],
        "name": "Ethylboronic acid",
        "notes": "Alkyl boronic acid; prone to β-hydride issues",
        "reaction_types": ["Suzuki-Miyaura"],
        "role": "nucleophile",
        "smiles": "CCB(O)O",
    },
    {
        "features": ["ArB(OH)2_reactant"],
        "name": "Pyridine-4-boronic acid",
        "notes": "Heteroaryl boronic acid; pyridine coordination risk",
        "reaction_types": ["Suzuki-Miyaura"],
        "role": "nucleophile",
        "smiles": "c1ccncc1B(O)O",
    },
    {
        "features": ["ArB(OH)2_reactant", "furan-diene_reactant"],
        "name": "Furan-2-boronic acid",
        "notes": "Five-membered heterocyclic boronic acid",
        "reaction_types": ["Suzuki-Miyaura"],
        "role": "nucleophile",
        "smiles": "c1coc(B(O)O)c1",
    },
    {
        "features": ["ArB(OH)2_reactant"],
        "name": "Thiophene-2-boronic acid",
        "notes": "Thiophene boronic acid; sulfur can coordinate",
        "reaction_types": ["Suzuki-Miyaura"],
        "role": "nucleophile",
        "smiles": "c1csc(B(O)O)c1",
    },
    {
        "features": ["ArNH2_reactant"],
        "name": "Aniline",
        "notes": "Aromatic primary amine; standard C-N coupling partner",
        "reaction_types": ["Buchwald-Hartwig", "Ullmann", "SNAr"],
        "role": "nucleophile",
        "smiles": "c1ccc(N)cc1",
    },
    {
        "features": ["Alkyl-H_reactant", "RNH2_reactant"],
        "name": "Ethylamine",
        "notes": "Primary aliphatic amine",
        "reaction_types": ["Buchwald-Hartwig", "Ullmann", "SNAr"],
        "role": "nucleophile",
        "smiles": "CCN",
    },
    {
        "features": ["Alkyl-H_reactant", "RNH2-a-branch_reactant", "RNH2_reactant"],
        "name": "Isopropylamine",
        "notes": "Branched primary amine; α-branching",
        "reaction_types": ["Buchwald-Hartwig", "Ullmann"],
        "role": "nucleophile",
        "smiles": "CC(C)N",
    },
    {
        "features": ["Alkyl-H_reactant", "RNH2_reactant"],
        "name": "tert-Butylamine",
        "notes": "Highly hindered primary amine",
        "reaction_types": ["Buchwald-Hartwig"],
        "role": "nucleophile",
        "smiles": "CC(C)(C)N",
    },
    {
        "features": ["Alkyl-H_reactant", "R2NH_reactant"],
        "name": "N-Methylethylamine",
        "notes": "Secondary aliphatic amine",
        "reaction_types": ["Buchwald-Hartwig", "Ullmann"],
        "role": "nucleophile",
        "smiles": "CCNC",
    },
    {
        "features": ["Alkyl-H_reactant", "ArNHR_reactant"],
        "name": "N-Methylaniline",
        "notes": "Secondary aromatic amine",
        "reaction_types": ["Buchwald-Hartwig", "Ullmann"],
        "role": "nucleophile",
        "smiles": "c1ccc(NC)cc1",
    },
    {
        "features": ["Alkyl-H_reactant"],
        "name": "N,N-Dimethylaniline",
        "notes": "Tertiary amine; not reactive in C-N coupling",
        "reaction_types": [],
        "role": "nucleophile",
        "smiles": "c1ccc(N(C)C)cc1",
    },
    {
        "features": ["Alkyl-H_reactant", "ArNH2_reactant"],
        "name": "4-Methoxyaniline",
        "notes": "Electron-rich aniline",
        "reaction_types": ["Buchwald-Hartwig", "Ullmann"],
        "role": "nucleophile",
        "smiles": "COc1ccc(N)cc1",
    },
    {
        "features": ["Ar-CN_reactant", "ArNH2_reactant"],
        "name": "4-Aminobenzonitrile",
        "notes": "Electron-poor aniline; less nucleophilic",
        "reaction_types": ["Buchwald-Hartwig", "Ullmann"],
        "role": "nucleophile",
        "smiles": "N#Cc1ccc(N)cc1",
    },
    {
        "features": ["ArNH2_reactant"],
        "name": "4-Aminopyridine",
        "notes": "Heteroaryl amine; pyridine coordination",
        "reaction_types": ["Buchwald-Hartwig"],
        "role": "nucleophile",
        "smiles": "Nc1ccncc1",
    },
    {
        "features": [],
        "name": "Indole",
        "notes": "NH heterocycle; can act as nucleophile",
        "reaction_types": ["Buchwald-Hartwig", "C-H activation"],
        "role": "nucleophile",
        "smiles": "c1ccc2[nH]ccc2c1",
    },
    {
        "features": ["ArNH2_reactant"],
        "name": "3-Aminopyrrole",
        "notes": "Heteroaryl amine with NH",
        "reaction_types": ["Buchwald-Hartwig"],
        "role": "nucleophile",
        "smiles": "c1c[nH]c(N)c1",
    },
    {
        "features": ["Alkyl-H_reactant", "ArNH2_reactant"],
        "name": "2-Methylaniline",
        "notes": "Ortho-substituted aniline; sterically hindered",
        "reaction_types": ["Buchwald-Hartwig", "Ullmann"],
        "role": "nucleophile",
        "smiles": "Nc1ccccc1C",
    },
    {
        "features": ["Alkyl-H_reactant", "ArNH2_reactant"],
        "name": "3,5-Dimethylaniline",
        "notes": "Meta-substituted aniline",
        "reaction_types": ["Buchwald-Hartwig"],
        "role": "nucleophile",
        "smiles": "Nc1cc(C)cc(C)c1",
    },
    {
        "features": ["Alkyl-H_reactant", "RNH2_reactant"],
        "name": "Benzylamine",
        "notes": "Benzylic amine; aliphatic but stabilized",
        "reaction_types": ["Buchwald-Hartwig", "Ullmann"],
        "role": "nucleophile",
        "smiles": "NCc1ccccc1",
    },
    {
        "features": ["ArOH_reactant"],
        "name": "Phenol",
        "notes": "Aromatic alcohol; C-O coupling partner",
        "reaction_types": ["Ullmann", "SNAr", "Mitsunobu"],
        "role": "nucleophile",
        "smiles": "c1ccc(O)cc1",
    },
    {
        "features": ["Alkyl-H_reactant", "ROH-primary_reactant"],
        "name": "Ethanol",
        "notes": "Simple aliphatic alcohol",
        "reaction_types": ["Ullmann", "Mitsunobu"],
        "role": "nucleophile",
        "smiles": "CCO",
    },
    {
        "features": [
            "Alkyl-H_reactant",
            "ROH-a-branch_reactant",
            "ROH-secondary_reactant",
            "isopropanol_reactant",
        ],
        "name": "Isopropanol",
        "notes": "Secondary alcohol",
        "reaction_types": ["Ullmann", "Mitsunobu"],
        "role": "nucleophile",
        "smiles": "CC(C)O",
    },
    {
        "features": [
            "Alkyl-H_reactant",
            "ROH-tertiary_reactant",
            "isopropanol_reactant",
        ],
        "name": "tert-Butanol",
        "notes": "Tertiary alcohol; sterically hindered",
        "reaction_types": ["Ullmann"],
        "role": "nucleophile",
        "smiles": "CC(C)(C)O",
    },
    {
        "features": ["Alkyl-H_reactant", "ArOH_reactant"],
        "name": "4-Methoxyphenol",
        "notes": "Electron-rich phenol",
        "reaction_types": ["Ullmann", "SNAr"],
        "role": "nucleophile",
        "smiles": "COc1ccc(O)cc1",
    },
    {
        "features": ["Ar-CN_reactant", "ArOH_reactant"],
        "name": "4-Hydroxybenzonitrile",
        "notes": "Electron-poor phenol; more acidic",
        "reaction_types": ["Ullmann", "SNAr"],
        "role": "nucleophile",
        "smiles": "N#Cc1ccc(O)cc1",
    },
    {
        "features": ["Alkyl-H_reactant", "ROH-primary_reactant"],
        "name": "Benzyl alcohol",
        "notes": "Benzylic alcohol",
        "reaction_types": ["Ullmann", "Mitsunobu"],
        "role": "nucleophile",
        "smiles": "OCc1ccccc1",
    },
    {
        "features": ["ArOH_reactant"],
        "name": "4-Hydroxypyridine",
        "notes": "Heteroaryl phenol",
        "reaction_types": ["Ullmann"],
        "role": "nucleophile",
        "smiles": "Oc1ccncc1",
    },
    {
        "features": ["ArSH_reactant", "RSH_reactant"],
        "name": "Thiophenol",
        "notes": "Aromatic thiol; strong nucleophile; catalyst poison risk",
        "reaction_types": ["Ullmann", "SNAr"],
        "role": "nucleophile",
        "smiles": "c1ccc(S)cc1",
    },
    {
        "features": ["Alkyl-H_reactant", "RSH_reactant"],
        "name": "Ethanethiol",
        "notes": "Aliphatic thiol; catalyst poison",
        "reaction_types": ["Ullmann", "SNAr"],
        "role": "nucleophile",
        "smiles": "CCS",
    },
    {
        "features": ["Alkyl-H_reactant", "RSH_reactant"],
        "name": "2-Propanethiol",
        "notes": "Secondary thiol",
        "reaction_types": ["Ullmann"],
        "role": "nucleophile",
        "smiles": "CC(C)S",
    },
    {
        "features": ["Alkyl-H_reactant"],
        "name": "Thioanisole",
        "notes": "Sulfide; not nucleophilic but can poison catalysts",
        "reaction_types": [],
        "role": "none",
        "smiles": "CSc1ccccc1",
    },
    {
        "features": ["acetylene_reactant", "alkyne-dienophile_reactant"],
        "name": "Acetylene",
        "notes": "Simplest terminal alkyne",
        "reaction_types": ["Sonogashira"],
        "role": "nucleophile",
        "smiles": "C#C",
    },
    {
        "features": [
            "Ar-alkyne_reactant",
            "alkyne-dienophile_reactant",
            "terminal-alkyne_reactant",
        ],
        "name": "Phenylacetylene",
        "notes": "Aryl-substituted terminal alkyne",
        "reaction_types": ["Sonogashira"],
        "role": "nucleophile",
        "smiles": "C#Cc1ccccc1",
    },
    {
        "features": [
            "Alkyl-H_reactant",
            "R-alkyne_reactant",
            "alkyne-dienophile_reactant",
            "terminal-alkyne_reactant",
        ],
        "name": "3,3-Dimethylbut-1-yne",
        "notes": "Sterically hindered terminal alkyne",
        "reaction_types": ["Sonogashira"],
        "role": "nucleophile",
        "smiles": "C#CC(C)(C)C",
    },
    {
        "features": ["Alkyl-H_reactant", "alkyne-dienophile_reactant"],
        "name": "Trimethylsilylacetylene",
        "notes": "TMS-protected alkyne; deprotectable",
        "reaction_types": ["Sonogashira"],
        "role": "nucleophile",
        "smiles": "C#C[Si](C)(C)C",
    },
    {
        "features": [
            "Alkyl-H_reactant",
            "R-alkyne_reactant",
            "alkyne-dienophile_reactant",
            "terminal-alkyne_reactant",
        ],
        "name": "Methyl propargyl ether",
        "notes": "Ether-substituted alkyne",
        "reaction_types": ["Sonogashira"],
        "role": "nucleophile",
        "smiles": "C#CCOC",
    },
    {
        "features": [
            "Ar-alkyne_reactant",
            "alkyne-dienophile_reactant",
            "terminal-alkyne_reactant",
        ],
        "name": "4-Ethynylpyridine",
        "notes": "Heteroaryl terminal alkyne",
        "reaction_types": ["Sonogashira"],
        "role": "nucleophile",
        "smiles": "C#Cc1ccncc1",
    },
    {
        "features": ["ArBr_reactant"],
        "name": "Phenylmagnesium bromide",
        "notes": "Grignard reagent for Kumada coupling",
        "reaction_types": ["Kumada"],
        "role": "nucleophile",
        "smiles": "[Mg]Brc1ccccc1",
    },
    {
        "features": ["Alkyl-H_reactant", "Alkyl-M_reactant", "RMgBr_reactant"],
        "name": "Ethylmagnesium bromide",
        "notes": "Alkyl Grignard",
        "reaction_types": ["Kumada"],
        "role": "nucleophile",
        "smiles": "CC[Mg]Br",
    },
    {
        "features": ["Ar-M_reactant", "RZnCl_reactant"],
        "name": "Phenylzinc chloride",
        "notes": "Organozinc for Negishi coupling",
        "reaction_types": ["Negishi"],
        "role": "nucleophile",
        "smiles": "Cl[Zn]c1ccccc1",
    },
    {
        "features": ["Alkyl-H_reactant", "Alkyl-M_reactant", "RZnBr_reactant"],
        "name": "Ethylzinc bromide",
        "notes": "Alkylzinc reagent",
        "reaction_types": ["Negishi"],
        "role": "nucleophile",
        "smiles": "CC[Zn]Br",
    },
    {
        "features": ["Alkyl-H_reactant"],
        "name": "Phenyltrimethylstannane",
        "notes": "Organotin for Stille coupling",
        "reaction_types": ["Stille"],
        "role": "nucleophile",
        "smiles": "c1ccc([Sn](C)(C)C)cc1",
    },
    {
        "features": ["Alkyl-H_reactant", "simple-dienophile_reactant"],
        "name": "Vinyltrimethylstannane",
        "notes": "Vinyl stannane",
        "reaction_types": ["Stille"],
        "role": "nucleophile",
        "smiles": "C=C[Sn](C)(C)C",
    },
    {
        "features": ["ArB(OH)2_reactant", "ArBr_reactant"],
        "name": "4-Bromophenylboronic acid",
        "notes": "Can act as both electrophile and nucleophile; selective coupling",
        "reaction_types": ["Suzuki-Miyaura"],
        "role": "bifunctional",
        "smiles": "Brc1ccc(B(O)O)cc1",
    },
    {
        "features": ["ArBr_reactant", "ArNH2_reactant"],
        "name": "4-Bromoaniline",
        "notes": "Both electrophile (Br) and nucleophile (NH2); orthogonal protection needed",
        "reaction_types": ["Buchwald-Hartwig", "Suzuki-Miyaura"],
        "role": "bifunctional",
        "smiles": "Brc1ccc(N)cc1",
    },
    {
        "features": ["ArBr_reactant", "ArOH_reactant"],
        "name": "4-Bromophenol",
        "notes": "Both electrophile (Br) and nucleophile (OH)",
        "reaction_types": ["Ullmann", "Suzuki-Miyaura"],
        "role": "bifunctional",
        "smiles": "Brc1ccc(O)cc1",
    },
    {
        "features": [
            "Ar-alkyne_reactant",
            "ArBr_reactant",
            "alkyne-dienophile_reactant",
            "terminal-alkyne_reactant",
        ],
        "name": "4-Bromophenylacetylene",
        "notes": "Both electrophile (Br) and nucleophile (alkyne)",
        "reaction_types": ["Sonogashira", "Suzuki-Miyaura"],
        "role": "bifunctional",
        "smiles": "Brc1ccc(C#C)cc1",
    },
    {
        "features": ["ArBr_reactant"],
        "name": "1,4-Dibromobenzene",
        "notes": "Two identical electrophilic sites; sp2_halide_site_count = 2",
        "reaction_types": ["Suzuki-Miyaura", "Buchwald-Hartwig"],
        "role": "di-electrophile",
        "smiles": "Brc1ccc(Br)cc1",
    },
    {
        "features": ["ArNH2_reactant"],
        "name": "1,4-Phenylenediamine",
        "notes": "Two identical nucleophilic sites",
        "reaction_types": ["Buchwald-Hartwig", "Ullmann"],
        "role": "di-nucleophile",
        "smiles": "Nc1ccc(N)cc1",
    },
    {
        "features": ["Alkyl-H_reactant", "ArBr_reactant", "Carbamate_reactant"],
        "name": "4-Bromo-N-Boc-aniline",
        "notes": "Boc-protected amine; prevents C-N coupling",
        "reaction_types": ["Suzuki-Miyaura", "Sonogashira"],
        "role": "electrophile",
        "smiles": "Brc1ccc(NC(=O)OC(C)(C)C)cc1",
    },
    {
        "features": ["Alkyl-H_reactant", "ArBr_reactant"],
        "name": "4-Bromo-TBS-phenol",
        "notes": "TBS-protected phenol",
        "reaction_types": ["Suzuki-Miyaura", "Sonogashira"],
        "role": "electrophile",
        "smiles": "Brc1ccc(O[Si](C)(C)C(C)(C)C)cc1",
    },
    {
        "features": [
            "Alkyl-H_reactant",
            "ArBr_reactant",
            "ArCOOR_reactant",
            "RCO2H_reactant",
            "RCO2OR_reactant",
        ],
        "name": "Methyl 4-bromobenzoate",
        "notes": "Ester-protected carboxylic acid",
        "reaction_types": ["Suzuki-Miyaura", "Buchwald-Hartwig"],
        "role": "electrophile",
        "smiles": "Brc1ccc(C(=O)OC)cc1",
    },
    {
        "features": ["ArBr_reactant", "ArCHO_reactant"],
        "name": "4-Bromobenzaldehyde",
        "notes": "Aldehyde functional group; can be reduced/oxidized",
        "reaction_types": ["Suzuki-Miyaura", "Buchwald-Hartwig", "Sonogashira"],
        "role": "electrophile",
        "smiles": "Brc1ccc(C=O)cc1",
    },
    {
        "features": ["Alkyl-H_reactant", "ArBr_reactant", "Bn-Br_reactant"],
        "name": "Pentamethylbromobenzene",
        "notes": "Extremely sterically hindered; requires bulky ligands",
        "reaction_types": ["Suzuki-Miyaura"],
        "role": "electrophile",
        "smiles": "Brc1c(C)c(C)c(C)c(C)c1C",
    },
    {
        "features": ["Alkyl-H_reactant", "ArBr_reactant"],
        "name": "4-Bromo-tert-butylbenzene",
        "notes": "Para-tert-butyl substituent",
        "reaction_types": ["Suzuki-Miyaura", "Buchwald-Hartwig"],
        "role": "electrophile",
        "smiles": "Brc1ccc(C(C)(C)C)cc1",
    },
    {
        "features": ["Alkyl-H_reactant", "RNH2_reactant"],
        "name": "tert-Butylamine",
        "notes": "Highly hindered primary amine; challenging substrate",
        "reaction_types": ["Buchwald-Hartwig"],
        "role": "nucleophile",
        "smiles": "CC(C)(C)N",
    },
    {
        "features": ["Alkyl-H_reactant", "ArNH2_reactant"],
        "name": "4-tert-Butylaniline",
        "notes": "Sterically hindered aniline",
        "reaction_types": ["Buchwald-Hartwig", "Ullmann"],
        "role": "nucleophile",
        "smiles": "CC(C)(C)c1ccc(N)cc1",
    },
    {
        "features": ["ArBr_reactant"],
        "name": "4-Bromonitrobenzene",
        "notes": "Highly electron-poor; very reactive in SNAr",
        "reaction_types": ["Suzuki-Miyaura", "Buchwald-Hartwig", "SNAr"],
        "role": "electrophile",
        "smiles": "Brc1ccc([N+](=O)[O-])cc1",
    },
    {
        "features": ["Alkyl-H_reactant", "ArBr_reactant"],
        "name": "4-Bromo-N,N-dimethylaniline",
        "notes": "Highly electron-rich; tertiary amine substituent",
        "reaction_types": ["Suzuki-Miyaura", "Sonogashira"],
        "role": "electrophile",
        "smiles": "Brc1ccc(N(C)C)cc1",
    },
    {
        "features": ["Alkyl-H_reactant", "ArBr_reactant"],
        "name": "1-Bromo-2,3,4,5-tetramethoxybenzene",
        "notes": "Extremely electron-rich; multiple methoxy groups",
        "reaction_types": ["Suzuki-Miyaura"],
        "role": "electrophile",
        "smiles": "COc1cc(OC)c(Br)c(OC)c1OC",
    },
    {
        "features": ["ArBr_reactant", "ArF_reactant"],
        "name": "Pentafluorobromobenzene",
        "notes": "Extremely electron-poor; multiple fluorines",
        "reaction_types": ["Suzuki-Miyaura", "SNAr"],
        "role": "electrophile",
        "smiles": "Fc1c(F)c(F)c(Br)c(F)c1F",
    },
]

PHASE_3_4_COMPOUNDS = [
    {
        "features": ["ArBr_reactant"],
        "name": "1,3,5-Tribromobenzene",
        "notes": "Polyhalogenated substrate; halogen_count=3",
        "reaction_types": ["Suzuki-Miyaura"],
        "role": "electrophile",
        "smiles": "Brc1cc(Br)cc(Br)c1",
    },
    {
        "features": ["ArBr_reactant", "ArF_reactant"],
        "name": "Pentafluorobromobenzene",
        "notes": "Polyhalogenated with fluorine EWG; halogen_count=6",
        "reaction_types": ["Suzuki-Miyaura"],
        "role": "electrophile",
        "smiles": "Fc1c(F)c(F)c(Br)c(F)c1F",
    },
    {
        "features": ["ArCl_reactant", "HetArCl_reactant"],
        "name": "2,5-Dichloropyridine",
        "notes": "Polyhalogenated heteroaryl; halogen_count=2",
        "reaction_types": ["Suzuki-Miyaura", "Buchwald-Hartwig"],
        "role": "electrophile",
        "smiles": "Clc1ccc(Cl)nc1",
    },
    {
        "features": ["ArCl_reactant", "ArI_reactant"],
        "name": "2,6-Dichloro-iodobenzene",
        "notes": "Mixed halides with ortho substitution; halogen_count=3",
        "reaction_types": ["Suzuki-Miyaura"],
        "role": "electrophile",
        "smiles": "Ic1c(Cl)cccc1Cl",
    },
    {
        "features": ["Alkyl-H_reactant", "ArBr_reactant"],
        "name": "2-tert-Butylbromobenzene",
        "notes": "Sterically hindered ortho-tert-butyl",
        "reaction_types": ["Suzuki-Miyaura"],
        "role": "electrophile",
        "smiles": "Brc1ccccc1C(C)(C)C",
    },
    {
        "features": ["Alkyl-H_reactant", "ArCl_reactant", "Bn-Cl_reactant"],
        "name": "3,5-Diisopropylchlorobenzene",
        "notes": "Multiple isopropyl substituents",
        "reaction_types": ["Suzuki-Miyaura"],
        "role": "electrophile",
        "smiles": "Clc1cc(C(C)C)ccc1C(C)C",
    },
    {
        "features": ["Alkyl-H_reactant", "ArI_reactant"],
        "name": "2,6-Dimethoxyiodobenzene",
        "notes": "Ortho-disubstituted with electron-donating groups",
        "reaction_types": ["Suzuki-Miyaura"],
        "role": "electrophile",
        "smiles": "Ic1c(OC)cccc1OC",
    },
    {
        "features": ["Alkyl-H_reactant", "ArBr_reactant", "Bn-Br_reactant"],
        "name": "Pentamethylbromobenzene",
        "notes": "Extremely sterically hindered; all positions substituted",
        "reaction_types": ["Suzuki-Miyaura"],
        "role": "electrophile",
        "smiles": "Brc1c(C)c(C)c(C)c(C)c1C",
    },
    {
        "features": ["Alkyl-H_reactant", "ArI_reactant", "Carbamate_reactant"],
        "name": "4-Iodo-N-Boc-aniline",
        "notes": "BOC-protected aniline",
        "reaction_types": ["Suzuki-Miyaura"],
        "role": "electrophile",
        "smiles": "Ic1ccc(NC(=O)OC(C)(C)C)cc1",
    },
    {
        "features": [
            "Alkyl-H_reactant",
            "ArBr_reactant",
            "Bn-Br_reactant",
            "Carbamate_reactant",
        ],
        "name": "4-Bromo-N-Cbz-aniline",
        "notes": "CBZ-protected aniline",
        "reaction_types": ["Suzuki-Miyaura"],
        "role": "electrophile",
        "smiles": "Brc1ccc(NC(=O)OCc2ccccc2)cc1",
    },
    {
        "features": [
            "Alkyl-H_reactant",
            "ArCl_reactant",
            "Bn-Cl_reactant",
            "Carbamate_reactant",
        ],
        "name": "4-Chloro-N-Fmoc-aniline",
        "notes": "FMOC-protected aniline with fluorenyl group",
        "reaction_types": ["Suzuki-Miyaura"],
        "role": "electrophile",
        "smiles": "Clc1ccc(NC(=O)OCC2c3ccccc3-c3ccccc32)cc1",
    },
    {
        "features": ["Alkyl-H_reactant", "ArBr_reactant"],
        "name": "4-Bromo-TBS-phenol",
        "notes": "TBS-protected phenol",
        "reaction_types": ["Suzuki-Miyaura"],
        "role": "electrophile",
        "smiles": "Brc1ccc(O[Si](C)(C)C(C)(C)C)cc1",
    },
    {
        "features": ["Alkyl-H_reactant", "ArI_reactant"],
        "name": "4-Iodo-TIPS-phenol",
        "notes": "TIPS-protected phenol",
        "reaction_types": ["Suzuki-Miyaura"],
        "role": "electrophile",
        "smiles": "Ic1ccc(O[Si](C(C)C)(C(C)C)C(C)C)cc1",
    },
    {
        "features": ["ArBr_reactant"],
        "name": "4-Bromonitrobenzene",
        "notes": "Strong electron-withdrawing nitro group",
        "reaction_types": ["Suzuki-Miyaura", "Buchwald-Hartwig"],
        "role": "electrophile",
        "smiles": "Brc1ccc([N+](=O)[O-])cc1",
    },
    {
        "features": ["Ar-CN_reactant", "ArCl_reactant"],
        "name": "4-Chlorobenzonitrile",
        "notes": "Strong electron-withdrawing nitrile group",
        "reaction_types": ["Suzuki-Miyaura", "Buchwald-Hartwig"],
        "role": "electrophile",
        "smiles": "Clc1ccc(C#N)cc1",
    },
    {
        "features": ["Alkyl-H_reactant", "ArBr_reactant"],
        "name": "4-Bromo-N,N-dimethylaniline",
        "notes": "Strong electron-donating dialkylamino group",
        "reaction_types": ["Suzuki-Miyaura"],
        "role": "electrophile",
        "smiles": "Brc1ccc(N(C)C)cc1",
    },
    {
        "features": ["Alkyl-H_reactant", "ArI_reactant"],
        "name": "4-Iodoanisole",
        "notes": "Strong electron-donating methoxy group",
        "reaction_types": ["Suzuki-Miyaura"],
        "role": "electrophile",
        "smiles": "Ic1ccc(OC)cc1",
    },
    {
        "features": ["ArBr_reactant"],
        "name": "2-Bromophenyl diphenylphosphine",
        "notes": "Ortho-phosphine for ligand synthesis; note: not itself a bidentate chelator",
        "reaction_types": ["Suzuki-Miyaura"],
        "role": "bifunctional",
        "smiles": "Brc1ccccc1P(c2ccccc2)c2ccccc2",
    },
    {
        "features": [
            "Alkyl-H-acidic_reactant",
            "Alkyl-H_reactant",
            "RCO2H_reactant",
            "RNH2-a-branch_reactant",
            "RNH2_reactant",
        ],
        "name": "Phenylalanine",
        "notes": "Amino acid with bidentate chelating ability; chiral_center_count=1",
        "reaction_types": ["Peptide coupling"],
        "role": "nucleophile",
        "smiles": "NC(Cc1ccccc1)C(=O)O",
    },
    {
        "features": [],
        "name": "Triphenylphosphine",
        "notes": "Common phosphine ligand",
        "reaction_types": ["Various cross-couplings"],
        "role": "ligand",
        "smiles": "c1ccc(P(c2ccccc2)c2ccccc2)cc1",
    },
    {
        "features": ["Alkyl-H_reactant"],
        "name": "1,8-Bis(dimethylphosphino)naphthalene",
        "notes": "Bidentate phosphine ligand (note: current SMARTS doesn't capture P-P bidentate pattern)",
        "reaction_types": ["Various cross-couplings"],
        "role": "ligand",
        "smiles": "c1ccc2c(c1)c(P(C)C)ccc2P(C)C",
    },
    {
        "features": ["Alkyl-H_reactant"],
        "name": "Ethane",
        "notes": "MW=30; low molecular weight test",
        "reaction_types": [],
        "role": "reference",
        "smiles": "CC",
    },
    {
        "features": ["anthracene_reactant"],
        "name": "Anthracene",
        "notes": "MW=178; medium molecular weight; fused rings",
        "reaction_types": [],
        "role": "reference",
        "smiles": "c1ccc2cc3ccccc3cc2c1",
    },
    {
        "features": ["anthracene_reactant"],
        "name": "Coronene",
        "notes": "MW=300; large polycyclic aromatic (note: not high_molecular_weight which requires MW>500)",
        "reaction_types": [],
        "role": "reference",
        "smiles": "c1ccc2cc3ccc4ccc5ccc6ccc1c7c2c3c4c5c67",
    },
    {
        "features": ["ArBr_reactant"],
        "name": "2-Bromonaphthalene",
        "notes": "Fused bicyclic aromatic system",
        "reaction_types": ["Suzuki-Miyaura", "Buchwald-Hartwig"],
        "role": "electrophile",
        "smiles": "Brc1ccc2ccccc2c1",
    },
    {
        "features": ["ArCl_reactant"],
        "name": "9-Chloroanthracene",
        "notes": "Tricyclic fused aromatic system",
        "reaction_types": ["Suzuki-Miyaura"],
        "role": "electrophile",
        "smiles": "Clc1ccc2c3ccccc3ccc2c1",
    },
    {
        "features": ["Alkyl-H_reactant"],
        "name": "Spiro[5.5]undecane",
        "notes": "Spirocyclic aliphatic system",
        "reaction_types": [],
        "role": "reference",
        "smiles": "C1CCC2(CC1)CCCC2",
    },
    {
        "features": ["Alkyl-H_reactant", "ArBr_reactant", "Bn-Br_reactant"],
        "name": "6-Bromo-spiro[chroman-2,1'-cyclohexane]",
        "notes": "Spirocyclic with aryl bromide",
        "reaction_types": ["Suzuki-Miyaura"],
        "role": "electrophile",
        "smiles": "Brc1ccc2c(c1)C1(CCCC1)CCCC2",
    },
    {
        "features": [
            "Alkyl-H-acidic_reactant",
            "Alkyl-H_reactant",
            "RCO2H_reactant",
            "RNH2-a-branch_reactant",
            "RNH2_reactant",
        ],
        "name": "(S)-Alanine",
        "notes": "Chiral amino acid; chiral_center_count=1",
        "reaction_types": ["Peptide coupling"],
        "role": "nucleophile",
        "smiles": "C[C@H](N)C(=O)O",
    },
    {
        "features": [
            "Alkyl-H_reactant",
            "ROH-a-branch_reactant",
            "ROH-secondary_reactant",
            "isopropanol_reactant",
        ],
        "name": "(2R,3R)-Butane-2,3-diol",
        "notes": "Two chiral centers; chiral_center_count=2",
        "reaction_types": [],
        "role": "reference",
        "smiles": "C[C@H](O)[C@H](C)O",
    },
    {
        "features": ["Alkyl-H_reactant"],
        "name": "(1R,3R,5S)-1,3,5-Trimethylcyclohexane",
        "notes": "Three chiral centers; chiral_center_count=3",
        "reaction_types": [],
        "role": "reference",
        "smiles": "C[C@H]1CC[C@@H](C)C[C@H]1C",
    },
    {
        "features": ["Alkyl-Br_reactant", "Alkyl-Cl_reactant", "Alkyl-H_reactant"],
        "name": "(R)-Bromochlorofluoromethane",
        "notes": "Chiral halomethane; chiral_center_count=1; halogen_count=3",
        "reaction_types": [],
        "role": "reference",
        "smiles": "Br[C@H](Cl)F",
    },
    {
        "features": ["ArBr_reactant", "ArCl_reactant"],
        "name": "2,4,5,6-Tetrachlorobromobenzene",
        "notes": "Highly polyhalogenated; halogen_count=5",
        "reaction_types": ["Suzuki-Miyaura"],
        "role": "electrophile",
        "smiles": "Clc1cc(Cl)c(Br)c(Cl)c1",
    },
    {
        "features": ["ArBr_reactant", "RCONHR_reactant"],
        "name": "4-Bromo-N-benzoylaniline",
        "notes": "Amide-protected aniline derivative",
        "reaction_types": ["Suzuki-Miyaura"],
        "role": "electrophile",
        "smiles": "Brc1ccc(NC(=O)c2ccccc2)cc1",
    },
    {
        "features": ["Alkyl-H_reactant"],
        "name": "(1S,2R,5S)-1,2,5-Trimethylcyclohexane",
        "notes": "Multiple stereogenic centers; chiral_center_count=3",
        "reaction_types": [],
        "role": "reference",
        "smiles": "C[C@@H]1CCC[C@@H](C)[C@@H]1C",
    },
]


def get_compounds_by_role(role: str) -> List[Dict[str, Any]]:
    """Get all compounds matching a specific role."""
    return [c for c in ARYL_HALIDES if c.get("role") == role]


def get_compounds_by_reaction(reaction_type: str) -> List[Dict[str, Any]]:
    """Get all compounds suitable for a specific reaction type."""
    return [c for c in ARYL_HALIDES if reaction_type in c.get("reaction_types", [])]


def get_compounds_by_feature(feature: str) -> List[Dict[str, Any]]:
    """Get all compounds with a specific calculable feature."""
    all_compounds = ARYL_HALIDES + PHASE_3_4_COMPOUNDS
    return [c for c in all_compounds if feature in c.get("features", [])]


ALL_SAMPLE_COMPOUNDS = ARYL_HALIDES + PHASE_3_4_COMPOUNDS

if __name__ == "__main__":
    print(f"Total sample compounds: {len(ALL_SAMPLE_COMPOUNDS)}")
    print("\nBreakdown by role:")
    print(f"  Electrophiles: {len(get_compounds_by_role('electrophile'))}")
    print(f"  Nucleophiles: {len(get_compounds_by_role('nucleophile'))}")
    print(f"  Bifunctional: {len(get_compounds_by_role('bifunctional'))}")
    print(
        "\nSample compounds for Suzuki-Miyaura: "
        + str(len(get_compounds_by_reaction("Suzuki-Miyaura")))
    )
    print(
        "Sample compounds for Buchwald-Hartwig: "
        + str(len(get_compounds_by_reaction("Buchwald-Hartwig")))
    )
