import { expect, test } from '@playwright/test'
import type { Page } from '@playwright/test'
import { readFile } from 'node:fs/promises'

test.skip(process.env.WEBUI_TEST_PLANNER !== '1', 'Use the dedicated planner config and deterministic API fixture')

async function start(page: Page, target = 'CCOC') {
  await page.goto('/')
  await page.getByRole('radio', { name: 'Interactive route planning', exact: true }).check()
  await page.getByLabel('Target molecule SMILES', { exact: true }).fill(target)
  await page.getByRole('button', { name: 'Start planning', exact: true }).click()
  await expect(page.getByText('0 selected steps', { exact: true })).toBeVisible()
}

async function expand(page: Page, molecule: string, strategy = 0) {
  await page.getByRole('button', { name: `Select ${molecule}`, exact: true }).click()
  await page.getByRole('button', { name: 'Find disconnections', exact: true }).click()
  await page.locator('.planner-candidate').nth(strategy).getByRole('button', { name: 'Add to tree' }).click()
}

test('builds three steps, revises a branch, restores history and exports the canonical route', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await start(page)
  await expect(page.getByRole('radio').last()).toHaveAccessibleName('Interactive route planning')
  const initialCard = (await page.locator('.planner-molecule').boundingBox())!
  const initialPreview = (await page.getByRole('region', { name: 'Target structure', exact: true }).boundingBox())!
  await expand(page, 'target')
  await expand(page, 'molecule 1.1')
  await expand(page, 'molecule 1.1/1.1')
  await expect(page.getByText('3 selected steps', { exact: true })).toBeVisible()
  const rootBranch = page.locator('.planner-tree-content > .molecule-branch')
  const alternatives = rootBranch.locator(':scope > .planner-alternatives > .reaction-branch')
  await expect(alternatives).toHaveCount(1)
  const children = alternatives.first().locator(':scope > .planner-precursors > .molecule-branch')
  await expect(children).toHaveCount(2)
  const rootBox = (await rootBranch.locator(':scope > .planner-molecule').boundingBox())!
  expect(rootBox.width).toBeCloseTo(initialCard.width, 0)
  const expandedPreview = (await page.getByRole('region', { name: 'Target structure', exact: true }).boundingBox())!
  expect(expandedPreview.width).toBeCloseTo(initialPreview.width, 0)
  expect(expandedPreview.height).toBeCloseTo(initialPreview.height, 0)
  const firstBox = (await children.nth(0).locator(':scope > .planner-molecule').boundingBox())!
  const secondBox = (await children.nth(1).locator(':scope > .planner-molecule').boundingBox())!
  expect(firstBox.y).toBeGreaterThan(rootBox.y + rootBox.height)
  expect(secondBox.y).toBeCloseTo(firstBox.y, 0)
  expect(secondBox.x).toBeGreaterThan(firstBox.x + firstBox.width)
  const grandchildren = children.nth(0).locator(':scope > .planner-alternatives > .reaction-branch > .planner-precursors > .molecule-branch')
  await expect(grandchildren).toHaveCount(2)
  const grandchildBox = (await grandchildren.nth(0).locator(':scope > .planner-molecule').boundingBox())!
  expect(grandchildBox.y).toBeGreaterThan(firstBox.y + firstBox.height)
  await children.nth(0).locator(':scope > .planner-molecule').getByRole('button', { name: 'Collapse alternatives' }).click()
  await expect(page.getByRole('button', { name: 'Select molecule 1.1/1.1', exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Select molecule 1.2', exact: true })).toBeVisible()
  await children.nth(0).locator(':scope > .planner-molecule').getByRole('button', { name: 'Expand 1 alternatives' }).click()
  await expect(page.getByRole('button', { name: 'Select molecule 1.1/1.1', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Select molecule 1.2', exact: true }).click()
  await page.getByRole('button', { name: 'Check supplier stock' }).click()
  await expect(page.getByText('Verified Stock Match · last check', { exact: true })).toBeVisible()
  await expect(page.getByText('4 unresolved molecules', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Use as starting material' }).click()
  await expect(page.getByText('1 user-designated starting materials', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Select target', exact: true }).click()
  await page.locator('.planner-candidate').nth(1).getByRole('button', { name: 'Add to tree' }).click()
  await expect(page.getByText('1 selected steps', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(page.getByText('3 selected steps', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Redo', exact: true }).click()
  await expect(page.getByText('1 selected steps', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await page.getByRole('button', { name: 'Find step conditions' }).click()
  await expect(page.getByText('Insufficient Evidence', { exact: true })).toBeVisible()
  const sessionDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export session', exact: true }).click()
  const sessionFile = (await (await sessionDownload).path())!
  const saved = JSON.parse(await readFile(sessionFile, 'utf8'))
  expect(saved.session.searches).toHaveLength(3)
  expect(Object.keys(saved.session.conditions)).toHaveLength(1)
  await page.reload()
  await page.getByRole('radio', { name: 'Interactive route planning', exact: true }).check()
  await expect(page.getByText('3 selected steps', { exact: true })).toBeVisible()
  await expect(page.getByText('1 user-designated starting materials', { exact: true })).toBeVisible()
  const routeDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export route', exact: true }).click()
  const route = JSON.parse(await readFile((await (await routeDownload).path())!, 'utf8'))
  expect(route.schema_version).toBe('2.0')
  expect(route.reaction_count).toBe(3)
  expect(route.root.reaction.children).toHaveLength(2)
  expect(route.root.reaction.evidence.evidence_kind).toBe('predicted')
  await page.getByRole('button', { name: 'Remove selected alternative' }).click()
  await expect(page.getByText('0 selected steps', { exact: true })).toBeVisible()
  await page.getByLabel('Import planning session').setInputFiles(sessionFile)
  await expect(page.getByText('3 selected steps', { exact: true })).toBeVisible()
  await page.screenshot({ path: '../../results/planner-desktop.png', fullPage: true })
  expect(errors).toEqual([])
})

test('keeps repeated molecules separate, empty searches unresolved, and exposes alternate realizations', async ({ page }) => {
  await start(page, 'CC')
  await expand(page, 'target')
  await page.getByRole('button', { name: 'Select molecule 1.1', exact: true }).click()
  await page.getByRole('button', { name: 'Use as starting material' }).click()
  await page.getByRole('button', { name: 'Select molecule 1.2', exact: true }).click()
  await page.getByRole('button', { name: 'Find disconnections' }).click()
  await expect(page.getByText(/No candidates found within this search scope/)).toBeVisible()
  await expect(page.getByText('1 unresolved molecules', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Use as starting material' }).click()
  await expect(page.getByText(/All branches end at user-designated starting materials/)).toBeVisible()
  await page.getByRole('button', { name: 'Reopen for planning' }).click()
  await expect(page.getByText('1 unresolved molecules', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'New target', exact: true }).click()
  await page.getByLabel('Target molecule SMILES', { exact: true }).fill('CCOC')
  await page.getByRole('button', { name: 'Start planning' }).click()
  await page.getByRole('button', { name: 'Find disconnections' }).click()
  await page.getByLabel('Strategy 1 precursor choice').selectOption('1')
  await expect(page.locator('.planner-reaction')).toHaveCount(0)
  await page.locator('.planner-candidate').first().getByRole('button', { name: 'Add to tree' }).click()
  await expect(page.getByRole('button', { name: 'Select molecule 1.1', exact: true })).toContainText('CCCl')
  await expect(page.locator('.planner-reaction')).toHaveCount(1)
})

test('rejects ancestor cycles and malformed imports without losing the route', async ({ page }) => {
  await start(page)
  await expand(page, 'target', 1)
  await page.getByRole('button', { name: 'Select molecule 1.1', exact: true }).click()
  await page.getByRole('button', { name: 'Find disconnections' }).click()
  await page.locator('.planner-candidate').nth(1).getByRole('button', { name: 'Add to tree' }).click()
  await expect(page.getByRole('alert')).toContainText('cycle')
  await expect(page.getByText('1 selected steps', { exact: true })).toBeVisible()
  await page.getByLabel('Import planning session').setInputFiles({ name: 'broken.json', mimeType: 'application/json', buffer: Buffer.from('{oops') })
  await expect(page.getByRole('alert')).toContainText('not valid JSON')
  await expect(page.getByText('1 selected steps', { exact: true })).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: '../../results/planner-mobile.png', fullPage: true })
})

test('explores multiple routes independently and retains them through switching and saving', async ({ page }) => {
  await start(page)
  await page.getByRole('button', { name: 'Find disconnections', exact: true }).click()
  await expect(page.locator('.planner-candidate')).toHaveCount(2)
  await expect(page.locator('.planner-reaction')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Undo', exact: true })).toBeDisabled()
  await expect(page.getByText('0 selected steps', { exact: true })).toBeVisible()
  await page.locator('.planner-candidate').first().getByRole('button', { name: 'Add to tree' }).click()
  await expect(page.locator('.planner-reaction')).toHaveCount(1)
  await expect(page.getByRole('button', { name: 'Select molecule 1.1', exact: true })).toContainText('CCO')
  await page.getByLabel('Strategy 1 precursor choice').selectOption('1')
  await expect(page.locator('.planner-reaction')).toHaveCount(1)
  await page.locator('.planner-candidate').first().getByRole('button', { name: 'Add to tree' }).click()
  await expect(page.locator('.planner-reaction')).toHaveCount(2)
  await page.locator('.planner-candidate').nth(1).getByRole('button', { name: 'Add to tree' }).click()
  await expect(page.locator('.planner-reaction')).toHaveCount(3)
  await page.getByRole('button', { name: 'Search again', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Search again', exact: true })).toBeEnabled()
  await expect(page.locator('.planner-reaction')).toHaveCount(3)
  await expect(page.getByRole('button', { name: 'Select molecule 3.1', exact: true })).toContainText('CCBr')
  await page.getByRole('button', { name: 'Use reaction 2', exact: true }).click()
  await expect(page.getByLabel('Strategy 1 precursor choice')).toHaveValue('1')
  await page.getByRole('button', { name: 'Use reaction 1', exact: true }).click()
  await expect(page.getByLabel('Strategy 1 precursor choice')).toHaveValue('0')
  await expand(page, 'molecule 1.1')
  await expect(page.getByText('2 selected steps', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Select molecule 3.1', exact: true }).click()
  await expect(page.getByText(/You are exploring an alternative branch/)).toBeVisible()
  await page.getByRole('button', { name: 'Find disconnections', exact: true }).click()
  await expect(page.locator('.planner-candidate')).toHaveCount(2)
  await expect(page.getByRole('button', { name: 'Select molecule 3.1/1.1', exact: true })).toHaveCount(0)
  await expect(page.locator('.planner-reaction')).toHaveCount(4)
  await expect(page.getByText('2 selected steps', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Use reaction 1', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.locator('.planner-candidate').first().getByRole('button', { name: 'Add to tree' }).click()
  await expect(page.getByRole('button', { name: 'Select molecule 3.1/1.1', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Use reaction 3', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('button', { name: 'Use reaction 1', exact: true })).toHaveAttribute('aria-pressed', 'false')
  await expect(page.getByRole('button', { name: 'Select molecule 1.1/1.1', exact: true })).toBeVisible()
  // Return directly to the first route without undoing exploration of the second.
  await page.getByRole('button', { name: 'Use reaction 1', exact: true }).click()
  await expect(page.locator('.planner-reaction.on-route')).toHaveCount(2)
  await expect(page.getByRole('button', { name: 'Select molecule 3.1/1.1', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Clear route choice' }).click()
  await expect(page.getByText('0 selected steps', { exact: true })).toBeVisible()
  await expect(page.locator('.planner-reaction')).toHaveCount(5)
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(page.getByText('2 selected steps', { exact: true })).toBeVisible()
  const exportEvent = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export session', exact: true }).click()
  const filename = (await (await exportEvent).path())!
  const saved = JSON.parse(await readFile(filename, 'utf8'))
  expect(saved.session.schema_version).toBe('interactive_planning.v2')
  expect(saved.session.root.alternatives).toHaveLength(3)
  expect(saved.session.root.alternatives[0].children[0].alternatives).toHaveLength(1)
  expect(saved.session.root.alternatives[2].children[0].alternatives).toHaveLength(1)
  await page.reload()
  await page.getByRole('radio', { name: 'Interactive route planning', exact: true }).check()
  await expect(page.locator('.planner-reaction')).toHaveCount(5)
  await expect(page.locator('.planner-reaction.on-route')).toHaveCount(2)
  await page.getByLabel('Import planning session').setInputFiles(filename)
  await expect(page.locator('.planner-reaction')).toHaveCount(5)
  await page.getByRole('button', { name: 'Focus molecule', exact: true }).click()
  const card = page.locator('.planner-molecule.selected')
  const desktopBox = (await card.boundingBox())!
  expect(desktopBox.width).toBe(170)
  const tree = page.getByRole('region', { name: 'Route tree', exact: true })
  expect(await tree.evaluate(element => element.scrollWidth > element.clientWidth)).toBe(true)
  await page.locator('.planner-tree-panel').screenshot({ path: '../../results/planner-alternative-routes.png' })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('button', { name: 'Focus molecule', exact: true }).click()
  const mobileBox = (await card.boundingBox())!
  expect(mobileBox.width).toBe(desktopBox.width)
  const preview = (await card.locator('.reaction-image').boundingBox())!
  expect(preview.height).toBe(94)
  const viewportBox = (await tree.boundingBox())!
  expect(mobileBox.x).toBeGreaterThanOrEqual(viewportBox.x)
  expect(mobileBox.x + mobileBox.width).toBeLessThanOrEqual(viewportBox.x + viewportBox.width)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('cancels stale searches on mode changes and permits recovery after failure', async ({ page }) => {
  await start(page, 'CCN')
  await page.getByRole('button', { name: 'Find disconnections' }).click()
  await expect(page.locator('.planner-progress').getByRole('status')).toContainText('Finding disconnections')
  await page.getByRole('radio', { name: 'Analyze reactions', exact: true }).check()
  await page.getByRole('radio', { name: 'Interactive route planning', exact: true }).check()
  await expect(page.getByRole('button', { name: 'Find disconnections' })).toBeEnabled()
  await page.getByRole('button', { name: 'Find disconnections' }).click()
  await expect(page.getByRole('alert')).toContainText('Fixture search unavailable')
  await expect(page.getByRole('button', { name: 'Find disconnections' })).toBeEnabled()
  await expect(page.getByText('1 unresolved molecules', { exact: true })).toBeVisible()
})
